name: flutter_txugcupload
description: 适用于 Flutter 的腾讯云点播上传 SDK
version: 0.1.0
homepage: https://github.com/leanflutter/flutter_txugcupload

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  plugin:
    platforms:
      android:
        package: org.leanflutter.plugins.flutter_txugcupload
        pluginClass: FlutterTxugcuploadPlugin
      ios:
        pluginClass: FlutterTxugcuploadPlugin
